assert 1 + 1 == 2, "int add"
assert 2 > 1 == True, "int greater True"
assert 2 > 3 == False, "int greater False"
assert 2 < 3 == True, "int smaller True"
assert 2 < 1 == False, "int smaller False"
assert (2 == 2) == True, "int equals True"
assert (2 == 3) == False, "int equals False"
assert 2 >> 1 == 1, "int rshift"
assert 2 << 1 == 4, "int lshift"
assert 2 * 3 == 6, "int mul"
assert 7 / 2 == 3, "int div"
assert str(777) == "777", "int str"
