assert bool([]) == False, "bool blank list"
assert bool([1]) == True, "bool list with element"
assert bool({}) == False, "bool blank dict"
assert bool({1:1}) == True, "bool dict with element"
assert bool(1) == True, "bool 1"
assert bool(-1) == True, "bool -1"
assert bool(-100) == True, "bool -100"
assert bool(0) == False, "bool 0"
assert bool("") == False, "bool blank str"
assert bool("abcd") == True, "bool str with content"
