assert ("abc" == "abc") == True, "str equals True"
assert ("abc" == "ab") == False, "str equals False"
assert ("abc" < "abcd") == True, "str smaller True"
assert ("abc" < "ab") == False, "str smaller False"
assert ("abc" > "ab") == True, "str greater True"
assert ("abc" > "abcd") == False, "str greater False"
assert "abc"[0] == "a", "str getitem first"
assert "abc"[2] == "c", "str getitem last"
assert str("abc") == "abc", "str str"
assert "ab%sef" % "cd" == "abcdef"
assert "%scdef" % "ab" == "abcdef"
assert "abcd%s" % "ef" == "abcdef"
